# Generated by Django 5.0.6 on 2024-06-26 21:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_pulse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_trips",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), blank=True, size=None
            ),
        ),
    ]
