# Generated by Django 5.0.6 on 2024-06-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_pulse", "0002_alter_user_user_trips"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_trips",
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=200)),
                ("start_date", models.CharField(max_length=200)),
                ("end_date", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="path_pulse.user",
                    ),
                ),
            ],
        ),
    ]
