# Generated by Django 5.0.6 on 2024-06-27 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_pulse", "0003_remove_user_user_trips_trip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="path_pulse.user"
            ),
        ),
    ]
