# Generated by Django 5.0.6 on 2024-06-27 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_pulse", "0004_alter_trip_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="path_pulse.user"
            ),
        ),
    ]
