# Generated by Django 5.0.6 on 2024-07-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("path_pulse", "0005_alter_trip_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="location",
            new_name="city",
        ),
        migrations.AddField(
            model_name="trip",
            name="country",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trip",
            name="state",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
